# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
env:
  global:
  - PKGNAME=rGEDI
matrix:
  include:
  - r: release
    os: linux
    env: BADGE=linux
    cache:
      - ccache
      - packages
    before_install:
      - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE)
        gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE)
        g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
  # osx libproj has a bug
  # - os: osx
  #   env:
  #     - BADGE=osx
  #     - LD_LIBRARY_PATH=" /opt/local/lib:$LD_LIBRARY_PATH"
  #     - CPATH="/opt/local/include:$CPATH"
  #   cache:
  #     - ccache
  #     - packages
  #   before_install:
  #     - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nVER=\nCCACHE=ccache\nCC=$(CCACHE)
  #       gcc$(VER) -std=gnu99\nCXX=$(CCACHE) g++$(VER)\nC11=$(CCACHE) g++$(VER)\nC14=$(CCACHE)
  #       g++$(VER)\nFC=$(CCACHE) gfortran$(VER)\nF77=$(CCACHE) gfortran$(VER)' > $HOME/.R/Makevars
  #     - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH="$(brew --prefix llvm)/bin:$PATH";
  #       fi
  - os: windows
    language: bash
    install:
      - choco install -y r --version 3.6.2
      - choco install -y rtools --version 3.5.0.4
      - "url=$(curl https://miktex.org/download | sed -n 's/.*href=.\\(.*x64.exe\\).*/https:\\/\\/miktex.org\\1/p' | head -1)"
      - if ! [ -f $HOME/AppData/Local/Temp/chocolatey/miktex.exe ]; then
        curl -Lo $HOME/AppData/Local/Temp/chocolatey/miktex.exe $url;
        curl -Lo oledlg.dll https://github.com/caiohamamura/flightplanning-R/releases/download/v0.0.0/oledlg.dll;
        fi
      - $HOME/AppData/Local/Temp/chocolatey/miktex.exe --unattended --auto-install=yes
      - "export PATH=/c/Program\\ Files/MiKTeX\\ 2.9/miktex/bin/x64:$PATH"
      - choco install -y pandoc
      - "export PATH=/c/Program\\ Files/R/R-3.6.2/bin/x64:/c/Rtools/bin:/c/Rtools/mingw_64/bin:$PATH"
      - mkdir -p ${HOME}/Documents/R/win-library/3.6
      - export R_LIBS_USER=${HOME}/Documents/R/win-library/3.6
      - echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' > .Rprofile
      - Rscript -e 'install.packages("devtools")'
      - Rscript -e 'install.packages(c("remotes"));if (!all(c("remotes") %in% installed.packages())) { q(status = 1, save = "no")}'
      - "Rscript -e 'deps <- remotes::dev_package_deps(dependencies = NA);remotes::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message(\"missing: \", paste(setdiff(deps$package, installed.packages()), collapse=\", \")); q(status = 1, save = \"no\")}'"

addons:
  apt:
    packages:
      - ccache
      - libgdal1-dev
      - libhdf5-serial-dev
      - libgsl-dev
      - libudunits2-dev
      - libglu1-mesa-dev
      - freeglut3-dev

  homebrew:
    packages:
      - ccache
      - pkg-config
      - gdal
      - gsl
      - hdf5
      - udunits
      - llvm

r_packages:
  - raster

language: r

script:
  - R CMD build .
  - R CMD check *tar.gz --as-cran
  - R CMD INSTALL . --build

after_script:
  - cat ${PKGNAME}.Rcheck/00check.log
  - cat ${PKGNAME}.Rcheck/00install.out

  # safelist
branches:
  only:
  - master
  - /^v[\d\.]*$/
before_deploy:
- 'export PKGVERSION=$(sed -n ''/^Version:/s/Version: \(.*\)/\1/p'' DESCRIPTION)'
- echo "Upload file glob is $(echo $PKGNAME)_${PKGVERSION}*"
deploy:
  provider: releases
  api_key:
    secure: FOoSwELB+ByvglrBJplIUGH9aI7/NCI5J+ga0wY35cZFZHBe4dNuUeE5gz6UfxCHDdoJN2+7gjjiLLVlKo+pK/Jx2Zxxep6U+R7Q/s1fbVCRbJaWV8hKEyg+Nk0VnzSD0K5xp0V2Ud3dbeGcueVu5ICyw53CEEotF4DoYqfzZPPV5oyn3X6aRrTE1a5XpPj6JutxSgLK2syQI+7bc5xwzLq7asO9zA3dOsDjk5IiVqCoTo4l8CxhXoKROBbl5uznZcs4D7Bc7Q4pp0OKgv+eWQpx3K9UWP8cheKXjMGyyglaTmVXXZYYKh+NOvnqEHclqT1MQTCzOIx6hxPKbDeUtE0/xWgPbfARL99LtO+bcHa1+nQsTvXkVIRjM785dbS2a4jcOR5CT41f3W5JyGxyp6dpXUm+4r0Z1z4i1y3VJXCEvQKlIqVnVuaxef0wdcfg73kFv8EPmLP6+nYigT9vaDyR7iN0bW3cfJ8Vfyo+ZDuX6uDB705fPiUD5Cs6arfRBbWkBePUmfd7C4bhm+zACJR60kQnzTSRHVYj7nARoSG4uzs161q+SWcqYx21dOjxYgQXiPVJhFsSja1N/A347P6uN6SVzf7UM+ofQUR8qNdMcFY23OIPBhu2JD50HisI8ZTppnJ14inA3P6SztfjglTKTuIYZyhrNDDlHD2FaUw=
  file_glob: true
  file: ${PKGNAME}_${PKGVERSION}*
  overwrite: true
  skip_cleanup: true
  on:
    repo: carlos-alberto-silva/rGEDI
    tags: true
